### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by kushtehlan** [dmfs/oauth2-essentials#17]
Hi, i am trying to implement this library.
I have a URL ("www.example.com") and i have a GET request for authorization code and POST request for access token. How can I implement this in scalatra framework. 
2. Here in credentials, we need client_id and password but i have only clientID and through that we can get authorization code. How to implement it without password

**Comment by dmfs** [comment]
I presume you want to implement the client side of OAuth2, right?

Sounds like the AuthorizationCodeGrant is what you want.

The `GET` request of an AuthorizationCodeGrant doesn't contain the client secret by design and this implementation won't add any secret to the URL. However, in general the authorization code token request contains both, client id and client secret.

I'm not familar with scalatra framework, so you have to be a little more specific with your question.

To me it sounds like you want to implement this in a server to authenticate with services that support OAuth2. The idea of AuthorizationCodeGrant is that the user authenticates in a browser and grants access to your application.

So what you have to do is to generate the initial URL and direct the user to this URL.
Just like in the README:
```java
// Start an interactive Authorization Code Grant
OAuth2InteractiveGrant grant = new AuthorizationCodeGrant(
    client, new BasicScope("scope"));

// Get the authorization URL and open it in a WebView
URI authorizationUrl = grant.authorizationUrl();
```

Send `authorizationUrl` to the client browser and open it. When the user granted access the service will redirect the browser to a specific URL that contains the access code. You need to get this URL (either by intercepting it in the Browser or by actually running an HTTP server at this address). Then feed the URL into `grant` like so:

```
// After the redirect, feed the URL to the grant to retrieve the access token
OAuth2AccessToken token = grant.withRedirect(redirectUrl).accessToken(executor);
```

In some cases the authorization service shows the access code in the browser and the user is expected to copy & paste it into the client application. We don't support this yet. Of course you could use the auth token to generate the redirect URL, but verification of that URL will fail because you can't provide the correct state string. Not sure if that problem is worth solving it, though. I don't really like authentication flows in which the user has to copy&paste any values.

**Comment by dmfs** [comment]
Make sure you use version 0.5.1. We've fixed a bug related to the Authorization Code Grant flow in 0.5. Also please let me know if your question has been answered sufficiently.
