### ISSUE TITLE
Ability to pass in state on `AuthorizationCodeGrant`

### ISSUE THREAD

**Issue by asikkema** [dmfs/oauth2-essentials#92]
We're using the lib server side against a service that has multiple instances running. In order to make sure that the state matches we would like to be able to pass this in through the constructor. However, this is private. Is there a workaround possible or perhaps the option to make that constructor public?

The error we're receiving now is: `org.dmfs.httpessentials.exceptions.ProtocolException: State in redirect uri doesn't match the original state!`

(Our current temporary workaround is to run on a single instance - this works in our test env, but not ready for prod).

Thanks!

**Comment by dmfs** [comment]
The original idea was to call the `state()` method, which returns a `Serializable` instance that can be used to restore the original Grant instance.

I can understand that this may not work well in a multi instance scenario.

Idea of the private constructor was to prevent anyone from using it incorrectly.

However, since all parts of the `State` objects are Strings (or can easily be serialized as such), I could imagine a method to serialize and de-serialize the state to/from a String. Would that work for you?

You'd use it like this:
```java
String state = grant.state().encoded();
```
and later
```
AuthorizationCodeGrant grant = new DecodedAuthorizationCodeGrantState(state).grant(oAuth2Client);
```

**Comment by dmfs** [comment]
To add to that, the state of an interactive grant consists of multiple values, some of which are random Strings. In order to restore the Grant instance all members need to be restored.
I'd like to keep them private to allow future extensions. For instance, adding support for RFC 7636 required adding a new, randomly generated string. By keeping this private, I was able to extend the class without breaking the API and every library user automatically benefits from the change if the OAuth2 provider supports it, without having to change anything (except for upgrading to the new version, of course).

**Comment by dmfs** [comment]
I went with a slightly different approach than outlined above and deprecated the `OAuth2GrantState` interface. Instead I've added an `encodedState` method directly to the `OAuth2InteractiveGrant`  interface. The encoded String can be converted back to an `OAuth2InteractiveGrant` by calling the ` value`  method on an `InteractiveGrantFactory` instance.

Please let me know, if that does not solve your problem.

**Comment by irttboopathy** [comment]
As @asikkema mentioned, we would run the multiple servers, and there is a need to store the state and code_verifier in Database, for further processing. By using BasicOAuth2Client, it is difficult to get those values. One way is to extend the class and save them in DB. But I guess if those values are extracted from grant, it would be helpful.
